#!/bin/bash

DIRECTORY="$(dirname "$(dirname "$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )")")"

function error {
  echo -e "\\e[91m$1\\e[39m"
  exit 1
}

echo -n "Checking for working systemd-binfmt..."
if ! sudo systemctl restart systemd-binfmt ;then
  echo -e "\nError: systemd-binfmt failed to restart. Running debug..."
  echo 'systemctl status systemd-binfmt.service'
  systemctl status systemd-binfmt.service
  echo 'systemctl status systemd-binfmt.service'
  journalctl -xe | cat
  error "Exiting now because systemd-binfmt failed to restart."
else
  echo "Done"
fi

sudo rm -f /etc/apt/sources.list.d/box86.list
echo "adding box86 repo..."
sudo wget https://itai-nelken.github.io/weekly-box86-debs/debian/box86.list -O /etc/apt/sources.list.d/box86.list || error "Failed to download /etc/apt/sources.list.d/box86.list"

echo "adding key..."
wget -qO- https://itai-nelken.github.io/weekly-box86-debs/debian/KEY.gpg | sudo apt-key add - || error "Failed to add key to box86 repo!"

echo "installing box86..."
"${DIRECTORY}/pkg-install" "box86" "$(dirname "$0")" || exit 1
 
rm -f Snipping-Tool_arm64.deb
wget -O Snipping-Tool_arm64.deb https://github.com/P-EO/Snipping-Tool/releases/download/v0.10.1/Snipping-Tool-0.10.1-1.debian-10.arm64.deb || error 'Failed to download Snipping-Tool deb file'
sudo apt install ./Snipping-Tool_arm64.deb -yf || error 'Failed to install Snipping-Tool'
rm -f Snipping-Tool_arm64.deb

